name: farmer_portal
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  sembast: ^2.1.2+3
  path_provider: ^1.5.1
  location: ^2.3.5
  geolocator: ^5.2.0
  font_awesome_flutter: ^8.5.0
  cloud_firestore: ^0.13.0+1
  translator: ^0.1.4
  url_launcher: ^5.4.1
  flutter_google_pay: ^0.1.4
  carousel_slider: ^1.4.1
  sliding_up_panel: ^1.0.0
  google_maps_flutter: ^0.5.25+1

  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/leaf.png
    - lib/assets/notifi.png
    - lib/assets/root.png
    - lib/assets/legumes.png
    - lib/assets/flower.png
    - lib/assets/bg.jpeg
    - lib/assets/tubers.png
    - lib/assets/product-1.jpg
    - lib/assets/product-2.jpg
    - lib/assets/product-3.jpg
    - lib/assets/product-4.jpg
    - lib/assets/product-5.jpg
    - lib/assets/product-6.jpg
    - lib/assets/product-7.jpg
    - lib/assets/product-8.jpg
    - lib/assets/product-9.jpg
    - lib/assets/product-10.jpg
    - lib/assets/product-11.jpg
    - lib/assets/product-12.jpg
    - lib/assets/image_4.jpg
    - lib/assets/image_5.jpg
    - lib/assets/image_6.jpg
    - lib/assets/category-2.jpg
    - lib/assets/category-3.jpg
    - lib/assets/category-4.jpg
    - lib/assets/Root/1.jpg
    - lib/assets/Root/2.jpg
    - lib/assets/Root/3.jpg
    - lib/assets/Root/4.jpg
    - lib/assets/Root/5.jpg
    - lib/assets/Root/6.jpg
    - lib/assets/Root/7.jpg
    - lib/assets/Root/8.jpg
    - lib/assets/Root/9.jpg
    - lib/assets/Root/10.jpg
    - lib/assets/Green/1.jpeg
    - lib/assets/Green/2.jpg
    - lib/assets/Green/3.png
    - lib/assets/Green/4.jpg
    - lib/assets/Green/5.jpg
    - lib/assets/Green/6.jpg
    - lib/assets/Green/7.jpg
    - lib/assets/Green/8.jpg
    - lib/assets/Green/9.jpg
    - lib/assets/Green/10.jpg
    - lib/assets/Green/11.jpg
    - lib/assets/Green/12.jpg
    - lib/assets/Green/13.jpg
    - lib/assets/Leaf/1.jpg
    - lib/assets/Leaf/2.jpg
    - lib/assets/Leaf/3.jpg
    - lib/assets/Leaf/4.jpg
    - lib/assets/Leaf/5.jpg
    - lib/assets/Leaf/6.jpg
    - lib/assets/Leaf/7.jpg
    - lib/assets/Spinach/1.jpg
    - lib/assets/Spinach/2.jpg
    - lib/assets/Spinach/3.jpg
    - lib/assets/Spinach/4.jpg
    - lib/assets/Spinach/5.jpg
    - lib/assets/Spinach/6.jpg
    - lib/assets/Spinach/7.jpg
    - lib/assets/Spinach/8.jpg
    - lib/assets/Spinach/9.jpg
    - lib/assets/Spinach/10.jpg
    - lib/assets/spinach.png
    - lib/assets/fruits.png
    - lib/assets/Fruits/1.jpg
    - lib/assets/Fruits/2.jpg
    - lib/assets/Fruits/3.jpg
    - lib/assets/Fruits/4.jpg
    - lib/assets/Fruits/5.jpg
    - lib/assets/Fruits/6.jpg
    - lib/assets/Fruits/7.jpg
    - lib/assets/Fruits/8.jpg
    - lib/assets/Fruits/9.jpg
    - lib/assets/Fruits/10.jpg
    - lib/assets/Fruits/11.jpg
    - lib/assets/Other/1.jpg
    - lib/assets/Other/2.jpg
    - lib/assets/Other/3.jpg
    - lib/assets/Other/4.jpg
    - lib/assets/Other/5.jpg
    - lib/assets/Other/6.jpg
    - lib/assets/Other.png
    - lib/assets/Legume/1.jpg
    - lib/assets/Legume/2.jpg
    - lib/assets/Legume/3.png
    - lib/assets/Legume/4.jpg
    - lib/assets/Legume/5.jpg
    - lib/assets/Legume/6.jpg
    - lib/assets/Legume/7.jpg
    - lib/assets/Legume/8.jpg
    - lib/assets/Legume/9.jpg 
    - lib/assets/Cereals/1.jpg
    - lib/assets/Cereals/2.jpg
    - lib/assets/Cereals/3.jpg
    - lib/assets/Cereals/4.jpg
    - lib/assets/Cereals/5.jpg
    - lib/assets/Cereals/6.jpg
    - lib/assets/cerials.png
    - lib/assets/cereals.png
    - lib/assets/Rice/1.jpg
    - lib/assets/Rice/2.jpg
    - lib/assets/Rice/3.jpg
    - lib/assets/Rice/4.jpg
    - lib/assets/Rice/5.jpg
    - lib/assets/Rice/6.jpg
    - lib/assets/Rice/7.jpg
    - lib/assets/Rice/8.jpg

    
    
    




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
